### ISSUE TITLE
filing this to keep track of gaps in the tab syncing!

### ISSUE THREAD

**Issue by dpastoor** [juliasilge/vetiver.dev#4]
* in the sync-tabs.html still need to eventually at least make sure the aria-active attributes
* consider implication of other tab panels across the site. This could interfere as the "language" thats being stored is really just the tab title.
  * one option could be to allow-list certain language names/otherwise
* other stuff?

**Comment by juliasilge** [comment]
Here is some slightly weird behavior to address:

- Go to <https://juliasilge.github.io/vetiver.dev/get-started/>
- Click one of the links in the "Installation" tabs
- Go back with your browser

Now neither the R or Python tab is selected. If you click somewhere else (like to ["Version"](https://juliasilge.github.io/vetiver.dev/get-started/version.html)) not only is neither R nor Python selected, but there is no content displayed in any of the tabs.

**Comment by dpastoor** [comment]
hmmm I get partial replication - definitely something going on

**Comment by dpastoor** [comment]
replication of the issue

https://user-images.githubusercontent.com/3196313/168491161-6568667c-2f82-4cfa-bcc9-67a2aa0fbbfd.mov

**Comment by juliasilge** [comment]
I can also see this behavior (tabs blanking out with neither selected) if I:

- Start at https://juliasilge.github.io/vetiver.dev/get-started/version.html
- Click "Show the code from previous steps" to expand the hidden code

**Comment by dpastoor** [comment]
ok - the issue seems to stem from the fact that when doing that backwards navigation _none_ of the panels seem to be selected (not even a default), hence all that lower content is also hidden. What I'm not sure of just yet is whether this is a quarto bug that would happen on any website, or something that the custom script is exacerbating.

**Comment by dpastoor** [comment]
need more precise targeting - tabset is not specific enough in the existing code. For example:

![image](https://user-images.githubusercontent.com/3196313/168492125-05ea717b-802f-4983-a176-f429e6fc2b7b.png)

inside also has an id that starts with tabset (that improperly then gets applied active when clicked too)

![image](https://user-images.githubusercontent.com/3196313/168492148-ab418276-06f5-4634-b779-64a7cc9d8d40.png)

hopefully can use some of the additional ID's to more precisely target
